                                                    Hypothesis Testing Assign

In [ ]:
'''Background:
Bombay hospitality Ltd. operates a franchise model for producing exotic Norwegian dinners throughout New England.
The operating cost for a franchise in a week (W) is given by the equation W = $1,000 + $5X, where X represents 
the number of units produced in a week. Recent feedback from restaurant owners suggests that this cost model may no longer be accurate,
as their observed weekly operating costs are higher.
Objective:
To investigate the restaurant owners' claim about the increase in weekly operating costs using hypothesis testing.
Data Provided:
•	The theoretical weekly operating cost model: W = $1,000 + $5X
•	Sample of 25 restaurants with a mean weekly cost of Rs. 3,050
•	Number of units produced in a week (X) follows a normal distribution with a mean (μ) of 600 units and a standard deviation (σ) of 25 units
'''

In [2]:
import numpy as np
from scipy import stats

In [ ]:
# H0: μ = 4000  (Theoretical weekly cost based on model)
# H1: μ > 4000  (Actual cost is higher than theoretical)

In [3]:
sample_mean = 3050                  # Sample mean cost (Rs.)
X_mean = 600                        # Mean weekly units produced
std_dev_X = 25                      # Std. deviation of weekly units
n = 25                              # Sample size
alpha = 0.05                        # Significance level
    


In [4]:
# Theoretical mean was alrady given in the model: W = 1000 + 5X

mu=1000+5*X_mean
std_dev_W=5*std_dev_X
Std_error =std_dev_W/np.sqrt(n)


In [5]:
# Now lets perform one sample Z-Test manually(using Z-Distribution)

Z_score=(sample_mean-mu)/Std_error
critical_value =stats.norm._ppf(1-alpha)

In [6]:
# calculating P-value 
p_value = 1 - stats.norm.cdf(Z_score)  


In [7]:
print("===== Hypothesis Testing Key values =====")
print(f"Theoretical Mean (μ): ($). {mu}")
print(f"Sample Mean (x̄): ($). {sample_mean}")
print(f"Standard Deviation (W): ($) {std_dev_W}")
print(f"Standard Error (SE): ($) {Std_error:.2f}")
print(f"Z-Score: {Z_score:.2f}")
print(f"Critical Value (Z at α = 0.05): {critical_value:.2f}")
print(f"P-Value: {p_value:.4f}")


===== Hypothesis Testing Key values =====
Theoretical Mean (μ): ($). 4000
Sample Mean (x̄): ($). 3050
Standard Deviation (W): ($) 125
Standard Error (SE): ($) 25.00
Z-Score: -38.00
Critical Value (Z at α = 0.05): 1.64
P-Value: 1.0000


In [8]:
alpha = 0.05
PVALUE= 1.0000

if p_value < alpha:
    print("Result: Reject the null hypothesis (H₀)")
    print("Conclusion: There is evidence that weekly costs have increased.")
else:
    print("Result: Fail to reject the null hypothesis (H₀)")
    print("Conclusion: The data does NOT support the claim that weekly costs have increased.")


Result: Fail to reject the null hypothesis (H₀)
Conclusion: The data does NOT support the claim that weekly costs have increased.


Explanation:

Theoretical Mean (μ): Rs. 4000

Sample Mean (x̄): Rs. 3050

My alternative hypothesis (H₁) is: the actual cost is higher than the theoretical cost, i.e., μ > 4000.
However, since 3050 < 4000, our sample mean is actually lower than the model predicts.
This contradicts the alternative hypothesis.

Also, the Z-score is negative: -38.00.

A negative Z-score in a right-tailed test means the test statistic lies far outside the rejection region (on the opposite side of the tail).

Our p-value is 1.0000, meaning there is essentially no evidence to reject the null hypothesis.


Therefore, our final decision is "Result: Fail to reject the null hypothesis (H₀)
Conclusion: The data does NOT support the claim that weekly costs have increased."










